# Generated by Django 4.2.16 on 2024-12-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('docente', 'Docente'), ('alumno', 'Alumno')], default='alumno', max_length=10),
        ),
    ]
